apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alex-postgres
spec: 
  project: default
  source:
    repoURL: https://github.com/atossTraining/argo2.git
    targetRevision: main
    path: postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: alexsnamespace
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
      